### ISSUE TITLE
FutureAPI效率改进建议

### ISSUE THREAD

**Issue by gpmn** [okcoin-okex/open-api-v3-sdk#28]
https://github.com/okcoin-okex/open-api-v3-sdk/blob/master/okex-go-sdk-api/futures_api.go#L235

newOrderParams FuturesNewOrderParams
最好改成
newOrderParams* FuturesNewOrderParams

这样少一次拷贝动作，返回值FuturesNewOrderResult也是。
futures api和swap api不是同一个人写的啊，风格差别好大

**Comment by ZhiweiWang** [comment]
赞同，sdk完善度不够

**Comment by lingtingfu** [comment]
最好是服务端能支持 protobuf，多语言 sdk 什么的，依赖接口定义文件就可以生成了。风格也统一。
