### ISSUE TITLE
WSEventResponse's Success field should be bool type

### ISSUE THREAD

**Issue by gpmn** [okcoin-okex/open-api-v3-sdk#29]
https://github.com/okcoin-okex/open-api-v3-sdk/blob/master/okex-go-sdk-api/ws_base.go#L89

Success应该是bool型号，否则无法反序列化lognin的json数据

{"event":"login","success":true}

**Comment by lingtingfu** [comment]
服务端的返回值 string type, 具体请参考 https://www.okex.me/docs/zh/#spot_ws-login
