### ISSUE TITLE
WSEventResponse.Valid需要考虑login消息

### ISSUE THREAD

**Issue by gpmn** [okcoin-okex/open-api-v3-sdk#30]
https://github.com/okcoin-okex/open-api-v3-sdk/blob/master/okex-go-sdk-api/ws_base.go#L93

似乎应该加上： r.Event == "login" ||

func (r *WSEventResponse) Valid() bool {
	return r.Event == "login" || (len(r.Event) > 0 && len(r.Channel) > 0)
}

**Comment by lingtingfu** [comment]
the logic added.
