### ISSUE TITLE
handleTableResponse will call callback too many times

### ISSUE THREAD

**Issue by gpmn** [okcoin-okex/open-api-v3-sdk#31]
https://github.com/okcoin-okex/open-api-v3-sdk/blob/b7bf8144760821803cd3629f599d1b0ba354ad37/okex-go-sdk-api/ws_agent.go#L205

如果我同时订阅了8个币的futures/swap,同一个order/position/trade消息，这里就会回调8次同一个函数。
同一table的，只用最后一次subscribe指定的callback吧。

我的库已经改了
https://github.com/gpmn/open-api-v3-sdk/blob/26e8b1d0e5378f2904705c77d2785121b1381e44/okex-go-sdk-api/ws_agent.go#L205

**Comment by lingtingfu** [comment]
handleTableResponse 是针对每个订阅的通用处理逻辑，不宜做个性化适配。
以上需求，建议通过调用 agent.Subscribe(channel, filter, nil) 时 ReceivedDataCallback  传空解决。
